- components/01-mixins/buttons/_buttons.scss
- components/01-mixins/general/_mixins.scss
- components/01-mixins/grid/_default_classes.scss
- components/01-mixins/grid/_mixins.scss
- components/01-mixins/grid/_responsive-utilities.scss
> Add some documentation to the globally defined mixins.

- CHANGELOG.md
- INSTALL.md
- components/_preview.twig
- gulpfile.js
Fixed JS issues both locally and on the server (Jenkins deploy).
> Feature/stij 157: Fixed JS issues.

- components/21-atoms/button-submit/README.md
- docs/06-mixins.md
> STIJ-84 added documentation

- components/21-atoms/description/README.md
> STIJ-86 added description atom documentation

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- components/31-molecules/building-blocks/gallery/README.md
- docs/01-index.md
> STIJ-156: Fixes some errors in the licensing and readme files.

- components/51-templates/blocks-overview/blocks-overview.twig
- components/51-templates/building-blocks-overview/building-blocks-overview.twig
- components/51-templates/buttons/buttons.twig
- components/51-templates/forms/forms.twig
- components/51-templates/grid/grid.twig
- components/51-templates/headings/headings.twig
- components/51-templates/icons-overview/icons-overview.twig
- components/51-templates/image-styles/image-styles.twig
- components/51-templates/lists/lists.twig
- components/51-templates/messages-overview/messages-overview.twig
- components/51-templates/paragraph-types/paragraph-types.twig
- components/51-templates/styleguide/styleguide.twig
- components/51-templates/tags/tags.twig
- components/styleguide.scss
> STIJ-163: Added fix for broken heading-2 atom.

- components/11-base/fonts/fonts.twig
- components/21-atoms/fieldset/fieldset.twig
- components/21-atoms/link/link.twig
- components/31-molecules/blocks/disclaimer-block/disclaimer-block.twig
- components/31-molecules/blocks/post-address-block/post-address-block.twig
- components/31-molecules/building-blocks/cta-link/cta-link.config.json
- components/31-molecules/building-blocks/pagination/pagination--state2.twig
- components/31-molecules/building-blocks/pagination/pagination--state3.twig
- components/31-molecules/building-blocks/pagination/pagination.twig
- components/31-molecules/building-blocks/search/search.config.json
- components/31-molecules/islands/gentinfo-island/gentinfo-island.twig
- components/31-molecules/islands/island/island.twig
- components/31-molecules/logo/logo.twig
- components/51-templates/building-blocks-overview/building-blocks-overview.twig
- components/61-layouts/forms/form-with-steps/form-with-steps.twig
> STIJ-162: Change all Dutch text to English.

- CHANGELOG.md
- components/21-atoms/button-submit/button-submit.config.json
- components/21-atoms/button-submit/button-submit.twig
- components/21-atoms/inputs/input-submit/README.md
> STIJ-159: Removed button submit atom.

- docs/01-index.md
- gulpfile.js
> STIJ-168: Changed title of style guide in UI and docs page.

- docs/07-javascript.md
> STIJ-161: Fixed links in documentation.

- components/21-atoms/inputs/input-date/input-date.functions.js
- components/21-atoms/inputs/input-date/input-date.twig
> STIJ-158: Change date format of datepicker.

- CHANGELOG.md
- components/21-atoms/icons/README.md
> STIJ-89: Changed the icon atom documentation to English and updated it.

- CHANGELOG.md
- components/31-molecules/building-blocks/search/README.md
> STIJ-106: Added search molecule documentation.

- CHANGELOG.md
- components/31-molecules/building-blocks/search/search.config.json
- components/31-molecules/building-blocks/search/search.twig
- components/41-organisms/header/_header.scss
- components/41-organisms/header/header.functions.js
- components/41-organisms/header/header.twig
> Feature/stij 170: Fixed search molecule.

- components/51-templates/forms/README.md
- components/51-templates/forms/forms--with-errors.twig
> STIJ-181: Added a forms preview variant without the error messages.

- CHANGELOG.md
- components/00-settings/_vars.scss
- components/01-mixins/themify/_themify.scss
- components/11-base/colors/README.md
- components/11-base/colors/colors.config.json
- components/11-base/section/section.twig
- components/31-molecules/building-blocks/cta-link/_cta-link.scss
- components/31-molecules/fields/_fields.scss
> STIJ-39: Fixed some colors and themify options.

- components/31-molecules/building-blocks/hamburger-menu/_hamburger-menu.scss
- components/31-molecules/building-blocks/mijn-gent-block/mijn-gent-block.twig
- components/41-organisms/header/_header.scss
- components/41-organisms/header/header--with-menu.twig
- components/41-organisms/header/header.config.json
- components/_preview-header.twig
- components/_preview.twig
> STIJ-173: Added header variant with a menu and one without a menu.

- CHANGELOG.md
- components/41-organisms/footer/footer.config.json
- components/_preview-footer.twig
> STIJ-182: Fixed whitespace in footer preview.

- CHANGELOG.md
- components/21-atoms/image/image.config.json
- components/31-molecules/islands/map-island/map-island.config.json
- components/51-templates/building-blocks-overview/building-blocks-overview.twig
- components/_preview-hamburger-menu.twig
- components/_preview-mijn-gent.twig
- components/_preview-without-padding.twig
- components/styleguide.scss
> STIJ-189: Style guide specific issues

- CHANGELOG.md
- components/21-atoms/paragraph/README.md
- components/21-atoms/paragraph/_paragraph.scss
- components/21-atoms/paragraph/paragraph.config.json
> STIJ-96: Updated paragraph documentation.

- CHANGELOG.md
- components/31-molecules/building-blocks/breadcrumbs/breadcrumbs.config.json
- components/31-molecules/building-blocks/gallery/gallery.config.json
- components/41-organisms/footer/footer.config.json
- components/_preview-breadcrumb.twig
- components/_preview-footer.twig
- components/_preview-gallery.twig
- components/_preview-input-multiselect-chosen.twig
- components/_preview-map-island.twig
> STIJ-199: Removed some obsolete preview layouts.

- package.json
> Updated to version 2.7.1

- docs/01-index.md
Updated the homepage of the style guide to better document the installation process.
After working with external developers we noticed the installation procedure documented properly inside https://stijlgids.stad.gent/
> STIJ-209: Updated the docs index.md 

- CHANGELOG.md
- components/styleguide.scss
- package.json
- postinstall.sh
> Feature/stij 207: Small preview fix.

- CHANGELOG.md
- postinstall.sh
> STIJ-208: Fixed bug in postinstall.sh script.

- CHANGELOG.md
- components/00-settings/_vars.scss
- components/01-mixins/themify/_themify.scss
- components/11-base/section/section.twig
- components/21-atoms/headings/_headings.scss
- components/21-atoms/headings/heading-1/_heading-1.scss
- components/21-atoms/headings/heading-2/_heading-2.scss
- components/21-atoms/headings/heading-3/_heading-3.scss
- components/21-atoms/headings/heading-4/_heading-4.scss
- components/21-atoms/headings/heading-5/_heading-5.scss
- components/21-atoms/headings/heading-6/_heading-6.scss
Changes titles color if it contains a link.
>  STIJ-197: Added margin top to headings + give tite links a link color.

- CHANGELOG.md
- components/31-molecules/building-blocks/cta-link/_cta-link.scss
- components/31-molecules/building-blocks/newsletter-block/_newsletter-block.scss
- components/31-molecules/teaser/_teaser.scss
- components/41-organisms/footer/_footer.scss
- components/51-templates/blocks-overview/blocks-overview.twig
- components/51-templates/building-blocks-overview/building-blocks-overview.twig
- components/51-templates/buttons/buttons.twig
- components/51-templates/collections-overview/collections-overview.twig
- components/51-templates/forms/forms--with-errors.twig
- components/51-templates/forms/forms.twig
- components/51-templates/grid/grid.twig
- components/51-templates/headings/headings.twig
- components/51-templates/icons-overview/icons-overview.twig
- components/51-templates/image-styles/image-styles.twig
- components/51-templates/lists/lists.twig
- components/51-templates/messages-overview/messages-overview.twig
- components/51-templates/paragraph-types/paragraph-types.twig
- components/51-templates/styleguide/styleguide.twig
- components/51-templates/tags/tags.twig
- components/styleguide.scss
Chaning the heading atoms in a previous PR broke some of the preview layouts. This PR aims to fix those issues.
> Fixed preview templates after refactoring the heading atoms.

- CHANGELOG.md
- components/41-organisms/teaser-collection/teaser-collection--masonry.twig
- components/41-organisms/teaser-collection/teaser-collection.binding.js
- components/_preview.twig
- package.json
- postinstall.sh
- yarn.lock
Added masonry-layout library.
Needed in 'scholen' site.
> STIJ-216: Added masonry-layout library

- CHANGELOG.md
- version_tag.sh
Added gulp validation check before the script continues deploying.
> Feature/STIJ-217: Added gulp validation check.

- components/41-organisms/teaser-collection/teaser-collection.binding.js
> STIJ-216: Fixed js validate issues

- CHANGELOG.md
- components/21-atoms/headings/_headings.scss
Remove header margin top. We need to think of a better way to integrate this throughout the components and sub projects using this style guide.
> STIJ-221: Remove header margin top again.

- components/31-molecules/fields/form-actions/_form-actions.scss
- components/31-molecules/fields/form-actions/form-actions--editor.twig
- components/31-molecules/fields/form-actions/form-actions.twig
- Solved floating issue for form actions.
- Made form action buttons use btn-inlineblock()
Form actions had a collapsed hight due to floated elements.
Fractal styleguide templates
> STIJ-235: Fixed form actions float issue.

- CHANGELOG.md
- components/11-base/base/_base.scss
- components/21-atoms/headings/heading-1/_heading-1.scss
- components/21-atoms/headings/heading-2/_heading-2.scss
- components/21-atoms/headings/heading-3/_heading-3.scss
- components/21-atoms/headings/heading-4/_heading-4.scss
- components/21-atoms/headings/heading-5/_heading-5.scss
- components/21-atoms/headings/heading-6/_heading-6.scss
- components/31-molecules/building-blocks/breadcrumbs/_breadcrumbs.scss
- components/31-molecules/building-blocks/breadcrumbs/breadcrumbs.twig
Fixed bug when breadcrumb titles would be too long and wrap to new line by splitting the line in two.
Bug fix.
> STIJ-236: Fixed breadcrumb wrapping issue and markup.

- CHANGELOG.md
- gulpfile.js
> STIJ-244: Fix critical bug to fix 2.8.0 branch.

- CHANGELOG.md
- components/21-atoms/link/README.md
- components/21-atoms/link/_link.scss
- components/21-atoms/link/link.config.json
- components/21-atoms/link/link.twig
> STIJ-93: Updated link documentation.

- CHANGELOG.md
- components/21-atoms/label/README.md
> STIJ-92: Added label documentation.

- CHANGELOG.md
- components/21-atoms/lists/README.md
- components/21-atoms/paragraph/README.md
> Feature/stij 96: updated paragraph atom

- CHANGELOG.md
- components/21-atoms/lists/list/README.md
> Feature/stij 94: Updated list atom

- CHANGELOG.md
- components/51-templates/collections-overview/collections-overview.twig
Small empty preview template bug fix.
> STIJ-250: Added content for teaser collections in preview layouts.

- components/21-atoms/tag/_tag.scss
- package.json
Link to ticket: **No linked ticket**
> Fixed compiling error on styleguide 2.9.1.
